language:
  - ruby
rvm:
  - 2.4.1
sudo: false
notifications:
  slack: shakacode:YvfXbuFMcFAHt6ZjABIs0KET
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
services:
  - postgresql
env:
  global:
    - RAILS_ENV=test
    - CXX=g++-4.9
install:
  - bundle install
  - chromedriver-update
  - nvm install stable && nvm alias default stable
  - npm install -g npm@5.3.x
  - npm install -g yarn
  - npm --version
  - yarn install
  - rake db:setup

# Tip: No need to run xvfb if running headless testing. However, we're going to start with
# Poltergeist and switch to selenium if a test fails.
before_script:
   - export DISPLAY=:99.0
   - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake db:schema:load
  - bundle exec rake
